sudo: true
language: cpp
dist: trusty
compiler:
- gcc
os:
- linux
before_script:
  - wget https://github.com/glfw/glfw/releases/download/3.1.2/glfw-3.1.2.zip
  - unzip glfw-3.1.2.zip
  - cd glfw-3.1.2
  - cmake .
  - make
  - sudo make install

 before_install:
  - git submodule update --init --recursive 
  
install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - unzip
    - libglfw-dev
    - libglew-dev
    - libglm-dev
    - libassimp-dev
    - libncurses5-dev
    - xorg-dev
    - libglu1-mesa-dev

script:
 - make
